[build]
  base = "./dist/playground"
  publish = "."

[[headers]]
  for = "/*"

  [headers.values]
    X-Content-Type-Options="nosniff"
    X-XSS-Protection="1; mode=block"
    Access-Control-Allow-Origin="*"

[[redirects]]
  from = "/documentation/examples/api/*"
  to = "https://amp.dev/documentation/examples/api/:splat"
  status = 200

[[redirects]]
  from = "/documentation/examples/*"
  to = "https://preview.amp.dev/documentation/examples/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "https://amp.dev/static/:splat"
  status = 200

[[redirects]]
  from = "/api/fetch"
  to = "/.netlify/functions/fetch"
  status = 200

[functions]
  directory = "./netlify/functions/"
